#!/usr/bin/python3
import getopt
import sys

from autoreadme_.autoreadme import *


def main(argv):
    """Args handling based on https://www.tutorialspoint.com/python/python_command_line_arguments.htm"""
    inputfile = scripts = outputfile = None
    try:
        opts, args = getopt.getopt(argv, "hi:s:o:", ["ifile=", "scripts=", "ofile="])
    except getopt.GetoptError:
        print("Usage:")
        print('rewritereadme.py -i <inputfile> -s <scriptsfolder> -o <outputfile>')
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            print('rewritereadme.py -i <inputfile> -s <scriptsfolder> -o <outputfile>')
            print(
                "Tags <<mycode1>>, <<mycode2>>, ...  in the inputfile will be replaced by the code and its output, using markdown syntax.")
            print("The first line in each script should be a comment containing a title for the code.")
            sys.exit()
        elif opt in ("-i", "--ifile"):
            inputfile = arg
        elif opt in ("-s", "--scripts"):
            scripts = arg
        elif opt in ("-o", "--ofile"):
            outputfile = arg
    if None in [inputfile, scripts, outputfile]:
        print("Usage:")
        print('rewritereadme.py -i <inputfile> -s <scriptsfolder> -o <outputfile>')
        sys.exit(2)
    rewrite(inputfile, scripts, outputfile)


if __name__ == "__main__":
    main(sys.argv[1:])
